services:
  # 1. Mock Product Service
  mock-product-service:
    build: 
      context: ./mock-product-service
      dockerfile: Dockerfile
    container_name: mock-product-service
    ports:
      - "8001:80"
    restart: always

  # 2. Core Service (BFF)
  core-service:
    build: 
      context: ./core-service
      dockerfile: Dockerfile
    container_name: core-service
    ports:
      - "8000:80"
    environment:
      MOCK_PRODUCT_SERVICE_URL: http://mock-product-service:80/
      REDIS_HOST: redis
      KAFKA_HOST: kafka:9092
    volumes:
      - ./core-service/app:/app/app
    depends_on:
      - mock-product-service
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 1

  # 3. Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: